name: maxi_sql
description: Library that serves as the foundation for the use, management, and execution of databases
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.8

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  maxi_framework:
  #git:
    #  url: https://github.com/MaxiCamilo/maxi_framework.git
    #  ref: main
    path: ../maxi_framework

  maxi_reflection:
    path: ../maxi_reflection

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
